---
title: "Exercise 2.1"
author: "Shunyi Huang"
date: "2022/9/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Q1: Provide server code which would allow the scatterplot to update the highlighted athletes depending
on the currently selected sports.

```{r}
library(shiny)
library(tidyverse)
olympics <- read_csv("https://uwmadison.box.com/shared/static/rzw8h2x6dp5693gdbpgxaf2koqijo12l.csv")
#' Scatterplot with highlighted points
#'
#' Assumes a column in df called "selected" saying whether points should be
#' larger / darker
# scatterplot <- function(df) {
#   ggplot(df) +
#     geom_point(
#     aes(Weight, `Height, cm`,
#     alpha = as.numeric(selected),
#     size = as.numeric(selected))
#     ) +
#     scale_alpha(range = c(0.05, .8)) +
#     scale_size(range = c(0.1, 1))
# }

#olympics$selected = sample(1, size = nrow(olympics), replace = TRUE)
olympics$selected = runif(nrow(olympics), 0, 1)
scatterplot <- function(df) {
  ggplot(df) +
    geom_point(
    aes(Weight, `Height, cm`),
    alpha = as.numeric(df$selected),
    size = as.numeric(df$selected))+
    scale_alpha(range = c(0.05, .8)) +
    scale_size(range = c(0.1, 1))
}

```


```{r}
ui <- fluidPage(
  #Front end interface
  selectInput("dropdown", "Select a Sport", choices = unique(olympics$Sport), multiple = TRUE),
  plotOutput("scatterplot")
)

server <- function(input, output) {
  #Back end logic
  output$scatterplot <- renderPlot({
    scatterplot(olympics[olympics$Sport == input$dropdown,])
  })
}


# server <- function(input, output) {
#   #Back end logic
#   df = olympics[olympics$Sport == renderText({input$choices}),]
#   output$scatterplot <- renderPlot({
#     scatterplot(df)
#   })
# }



shinyApp(ui,server)
```


```{r}

```







